<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TronicPocketPrinter.Core</RootNamespace>
    <AssemblyName>TronicPocketPrinter.Core</AssemblyName>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="PDFtoImage" Version="4.1.1" />
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>

</Project>
